name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # L'étape "flutter build" manuelle a été supprimée d'ici.
      # C'est l'action ci-dessous qui va s'en charger proprement.

      - name: Deploy to GitHub Pages
        uses: BluefireTeam/flutter-gh-pages@v9  # Passage à la V9 qui supprime l'erreur de renderer
        with:
          targetBranch: gh-pages
          baseHref: /portfolio/       # Remplacez par le nom de votre dépôt GitHub
